package model;
//Miguel

enum ListaTerritorios {
	AFRICA_DO_SUL, ANGOLA, ALGERIA,
	EGITO, NIGERIA, SOMALIA,
	ALASCA, CALGARY, CALIFORNIA,
	GROELANDIA, MEXICO, NOVAYORK,
	QUEBEC, TEXAS, VANCOUVER,
	ARGENTINA, BRASIL, PERU,
	VENEZUELA, ARABIA_SAUDITA, BANGLADESH,
	CAZAQUISTAO, CHINA, COREIA_DO_NORTE,
	COREIA_DO_SUL, ESTONIA, INDIA,
	IRA, IRAQUE, JAPAO,
	JORDANIA, LETONIA, MONGOLIA,
	PAQUISTAO, RUSSIA, SIBERIA,
	SIRIA, TAILANDIA, TURQUIA,
	ESPANHA, FRANCA, ITALIA,
	POLONIA, REINO_UNIDO, ROMENIA,
	SUECIA, UCRANIA, AUSTRALIA,
	INDONESIA, NOVAZELANDIA, PERTH
}

